# Name of the project
PROJECT_NAME = ElectronicHelper

BUILD:
	gcc ElectronicHelper.c test/test_electronichelper.c inc/ElectronicHelper.h -lm unity/unity.c -Iunity -Itest -Iinc -o ElectronicHelper.out

RUN:
	./ElectronicHelper.out

